# Generated by Django 2.2.11 on 2020-06-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_make_old_projects_public_again"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="machinery_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("translation-memory", "Translation memory"),
                    ("machine-translation", "Machine translation"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
